spring:
  application:
    name: leyou-gateway
server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api
  routes:
    leyou-item-service: /item/**